"""
Telegram notifier for the 4-agent sports betting pipeline.

Sends live progress updates to Telegram as each agent runs:
  - Batch start/end
  - Max: events found + research thesis
  - Nova: edges found per event
  - Lumi: risk verdicts + flags
  - Sage: approved picks
  - Agent group discussion (generated by Sage/Claude)

Reuses TG_BOT_TOKEN and TG_CHAT_ID from tg_bot.py.
All methods are non-blocking — failures are logged but never crash the pipeline.
"""

import os
import logging
import requests
from datetime import datetime, timezone

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

logger = logging.getLogger("agents.notifier")

# Reuse same bot/chat as tg_bot.py
BOT_TOKEN = os.getenv("TG_BOT_TOKEN", "")
CHAT_ID   = os.getenv("TG_CHAT_ID",   "")


def send(text: str) -> bool:
    """Send an HTML-formatted message to Telegram. Never raises."""
    if not BOT_TOKEN or not CHAT_ID:
        logger.debug("[TG] No credentials — skipping notification")
        return False
    try:
        r = requests.post(
            f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage",
            json={"chat_id": CHAT_ID, "text": text, "parse_mode": "HTML"},
            timeout=10,
        )
        if not r.ok:
            logger.warning(f"[TG] Send failed: {r.status_code} {r.text[:100]}")
        return r.ok
    except Exception as e:
        logger.warning(f"[TG] Send error: {e}")
        return False


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%d %b %Y %H:%M UTC")


def _sport_short(sport_key: str) -> str:
    """Convert 'basketball_nba' → 'NBA'."""
    parts = sport_key.split("_")
    return parts[-1].upper() if parts else sport_key.upper()


# ─── Per-agent notifications ──────────────────────────────────────────────────

def batch_start(sports: list, hours_ahead: int):
    sport_labels = " | ".join(_sport_short(s) for s in sports[:5])
    send(
        f"🤖 <b>Agent Pipeline Started</b>\n"
        f"Sports: {sport_labels}\n"
        f"Window: next {hours_ahead}h\n"
        f"<i>{_now()}</i>"
    )


def batch_no_candidates():
    send("🔍 <b>Max</b> — No events found this run. Pipeline sleeping.")


def max_done(report: dict):
    candidates = report.get("candidates", [])
    if not candidates:
        send("🔍 <b>Max</b> — No events worth researching found.")
        return

    verdict_emoji = {
        "HOME_ADVANTAGE": "🏠",
        "AWAY_EDGE":      "✈️",
        "NEUTRAL":        "⚖️",
        "UNCERTAIN":      "❓",
    }

    lines = [f"🔍 <b>Max</b> — {len(candidates)} event(s) researched:"]
    for c in candidates:
        emoji = verdict_emoji.get(c.get("max_verdict", ""), "❓")
        league = c.get("league", "?")
        home   = c.get("home_team", "?")
        away   = c.get("away_team", "?")
        conf   = c.get("confidence", "?")
        thesis = c.get("research", {}).get("edge_thesis", "")
        lines.append(f"\n  {emoji} <b>{league}</b>: {home} vs {away} [{conf}]")
        if thesis:
            # Show up to the first sentence break, max 240 chars
            first_sentence = thesis.split(". ")[0]
            display = first_sentence if len(first_sentence) <= 240 else thesis[:240]
            lines.append(f"     <i>{display}</i>")

    send("\n".join(lines))


def nova_done(report: dict):
    analyses = report.get("analyses", [])
    if not analyses:
        note = report.get("note", "")
        msg = "📊 <b>Nova</b> — No analyses produced."
        if note:
            msg += f"\n<i>{note}</i>"
        else:
            msg += "\n<i>Check ODDS_API_KEY and Polymarket connectivity.</i>"
        send(msg)
        return

    value_count = sum(1 for a in analyses if a.get("nova_verdict") == "VALUE")
    verdict_emoji = {
        "VALUE":      "🟢",
        "FAIR":       "🟡",
        "OVERPRICED": "🔴",
        "NO_MARKET":  "⚫",
        "UNKNOWN":    "⚪",
    }

    lines = [f"📊 <b>Nova</b> — {len(analyses)} analysed, {value_count} VALUE:"]
    for a in analyses:
        verdict = a.get("nova_verdict", "?")
        emoji   = verdict_emoji.get(verdict, "❓")
        eid     = a.get("event_id", "?")[:35]
        edge    = a.get("edge") or {}
        edge_pct   = edge.get("edge_pct", 0)
        selection  = edge.get("selection", "")
        poly_price = edge.get("polymarket_price", 0)
        sharp_prob = edge.get("sharp_prob", 0)

        lines.append(f"\n  {emoji} <b>{eid}</b> | {verdict}")
        if verdict == "VALUE" and selection:
            lines.append(
                f"     Back: <b>{selection}</b>\n"
                f"     Poly: {poly_price:.0%} vs Sharp: {sharp_prob:.0%} "
                f"→ +{edge_pct:.1f}% edge"
            )

    blind = sum(1 for a in analyses if a.get("nova_verdict") in ("UNKNOWN", "NO_MARKET"))
    if blind:
        lines.append(f"\n  ⚪ {blind} event(s) had no odds data (UNKNOWN/NO_MARKET) — check logs")

    send("\n".join(lines))


def lumi_done(report: dict):
    assessments = report.get("assessments", [])
    if not assessments:
        send("⚠️ <b>Lumi</b> — No risk assessment available.")
        return

    counts = {"PROCEED": 0, "CAUTION": 0, "ABORT": 0}
    for a in assessments:
        v = a.get("lumi_verdict", "?")
        counts[v] = counts.get(v, 0) + 1

    verdict_emoji = {"PROCEED": "✅", "CAUTION": "⚠️", "ABORT": "❌"}

    lines = [
        f"⚠️ <b>Lumi</b> — "
        f"✅ {counts['PROCEED']}  ⚠️ {counts['CAUTION']}  ❌ {counts['ABORT']}"
    ]
    for a in assessments:
        verdict = a.get("lumi_verdict", "?")
        emoji   = verdict_emoji.get(verdict, "❓")
        eid     = a.get("event_id", "?")[:35]
        lines.append(f"\n  {emoji} {eid}")

        if verdict == "ABORT":
            reason = a.get("skip_reason") or ""
            lines.append(f"     <i>SKIP: {reason[:120]}</i>")
        elif verdict == "CAUTION":
            risks = a.get("risks") or []
            if risks:
                desc = risks[0].get("description", "")
                lines.append(f"     <i>Watch: {desc[:120]}</i>")

    send("\n".join(lines))


def sage_done(report: dict):
    picks = report.get("picks", [])
    if not picks:
        send(
            "🧠 <b>Sage</b> — No bets approved this run.\n"
            "<i>Edge wasn't clean enough. Patience is profitable.</i>"
        )
        return

    lines = [f"🧠 <b>Sage</b> — {len(picks)} bet(s) APPROVED:"]
    for p in picks:
        prob   = float(p.get("model_probability", 0))
        conf   = p.get("confidence", "?")
        league = p.get("league", "?")
        sel    = p.get("selection", "?")
        notes  = p.get("notes", "")[:140]
        start  = p.get("event_start", "")[:16].replace("T", " ")

        lines.append(
            f"\n  🎯 <b>{league}</b> — <b>{sel}</b>\n"
            f"     Prob: {prob:.0%} | Conf: {conf} | Starts: {start}\n"
            f"     <i>{notes}</i>"
        )

    send("\n".join(lines))


def bets_placed(execution_results: list):
    """Send per-pick execution summary (LIVE/PAPER/SKIPPED/FAILED) to Telegram."""
    placed = [r for r in execution_results if r["status"] == "placed"]
    paper  = [r for r in execution_results if r["status"] == "paper"]

    label = "Placed" if placed else "Simulated" if paper else "Failed"
    mode  = "LIVE"   if placed else "PAPER"     if paper else ""

    lines = [f"💰 <b>Bets {label} ({mode})</b> — {len(execution_results)} pick(s)"]
    for r in execution_results:
        pick = r.get("pick", {})
        sel  = pick.get("selection", "?")
        lg   = pick.get("league", "?")
        st   = r["status"]
        p    = r.get("price", 0.0)
        sz   = r.get("size_usd", 0.0)
        oid  = r.get("order_id", "")

        if st in ("placed", "paper"):
            shares  = round(sz / p, 2) if p > 0 else 0
            oid_str = f"\n     Order: <code>{oid[:24]}</code>" if oid else ""
            icon    = "🟢" if st == "placed" else "🔵"
            lines.append(
                f"\n  {icon} [{'LIVE' if st == 'placed' else 'PAPER'}] "
                f"<b>{lg}</b> — <b>{sel}</b>\n"
                f"     ${sz:.2f} → {shares} shares @ {p:.4f}{oid_str}"
            )
        else:
            lines.append(
                f"\n  🔴 {'SKIPPED' if st == 'skipped' else 'FAILED'} "
                f"<b>{lg}</b> — {sel}\n"
                f"     <i>{r.get('reason', '')[:120]}</i>"
            )

    send("\n".join(lines))


def agent_discussion(text: str):
    """Send the agents' group discussion generated by Sage."""
    send(f"💬 <b>Agent Discussion</b>\n\n{text}")


def batch_done(picks_count: int, candidates_count: int, elapsed_s: float):
    mins = int(elapsed_s // 60)
    secs = int(elapsed_s % 60)
    send(
        f"✅ <b>Batch Complete</b>\n"
        f"Researched: {candidates_count} events\n"
        f"Approved bets: {picks_count}\n"
        f"Time: {mins}m {secs}s\n"
        f"<i>{_now()}</i>"
    )


def pipeline_error(step: str, error: str):
    send(
        f"🚨 <b>Pipeline Error — {step}</b>\n"
        f"<code>{str(error)[:300]}</code>"
    )
